#theme: jekyll-theme-tactile
title: Charlie Ruppe
#description: this is my website.

remote_theme: pages-themes/tactile@v0.2.0

permalink: pretty

author:
  name: Charlie Ruppe
  email: ruppe dot charlie @gmail.com

collections:
  demos:
    output: true
    permalink: /demos/:path/


plugins:
  - jektex
  - jekyll-remote-theme

exclude:
  - ".jekyll-cache"
  - ".jektex-cache"

kramdown:
  # This tells Kramdown to pass the math content through as-is, 
  # which should prevent it from leaving the original text behind.
  math_engine: null